/* Written by hand: the upstream file is generated by CMake, which this
   vendored subset does not use. Only the crypto sources are built here,
   and every target has these headers. */

#ifndef MZ_CONFIG_H
#define MZ_CONFIG_H

/* CZipReader reads AES encrypted archives, so the WinZip AES code is needed */
#define HAVE_WZAES

#define HAVE_DIRENT_H 1
#define HAVE_SYS_DIRENT_H 0
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_PDIR 1
#define HAVE_FSEEKO 1
#define HAVE_SYMLINK 1
#define HAVE_READLINK 1

#endif
